from __future__ import annotations

from pathlib import Path
from typing import Dict, Any, List
import time

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import json
import re

# 设置中文字体支持，避免字体缺失警告
# macOS 使用 STHeiti/Hiragino Sans GB，Linux 使用 SimHei/WenQuanYi，最后回退到 DejaVu Sans
_CHINESE_FONTS = ["STHeiti", "Hiragino Sans GB", "Heiti TC", "Songti SC", "SimHei", "WenQuanYi Micro Hei", "DejaVu Sans"]
plt.rcParams["font.sans-serif"] = _CHINESE_FONTS
plt.rcParams["axes.unicode_minus"] = False  # 正确显示负号


MEDIA_DIR = Path("backend/data/autoplan/media")
MEDIA_DIR.mkdir(parents=True, exist_ok=True)


def generate_boq_chart(boq_stats: Dict[str, Any]) -> List[str]:
    paths: List[str] = []
    if not boq_stats:
        return paths
    labels = ["item_count", "total_quantity", "density"]
    values = [
        float(boq_stats.get("item_count") or 0),
        float(boq_stats.get("total_quantity") or 0),
        float(boq_stats.get("density") or 0),
    ]
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar(labels, values, color=["#2f7ed8", "#0d233a", "#8bbc21"])
    ax.set_title("BoQ 统计概览")
    ax.set_ylabel("数值")
    fig.tight_layout()
    fname = f"boq_stats_{int(time.time())}.png"
    out = MEDIA_DIR / fname
    fig.savefig(out)
    plt.close(fig)
    paths.append(str(out))
    return paths


def generate_ingested_previews(limit: int = 6, project_id: str | None = None) -> List[str]:
    """
    Build a small gallery of drawing/attachment previews to make DOCX “图文并茂”.
    Sources:
    - backend/data/audit/ingest.jsonl records (latest first)
    - Prefer `preview_saved_as` generated by ingest; fallback to generate on the fly
    """
    audit_path = Path("backend/data/audit/ingest.jsonl")
    if not audit_path.exists():
        return []

    try:
        with audit_path.open("r", encoding="utf-8", errors="ignore") as f:
            lines = f.read().splitlines()[::-1]
    except Exception:
        return []
    picks: List[dict] = []
    pid = str(project_id).strip() if isinstance(project_id, str) and project_id.strip() else None
    for ln in lines:
        if len(picks) >= max(0, int(limit or 0)):
            break
        try:
            rec = json.loads(ln)
        except Exception:
            continue
        if pid is not None and str(rec.get("project_id") or "").strip() != pid:
            continue
        filename = (rec.get("filename") or "").strip()
        if not filename:
            continue
        name = filename.lower()
        # Heuristic: prefer drawings, exclude obvious tender/boq documents.
        tags = rec.get("tags") or []
        if "logo" in tags:
            continue
        is_drawing = ("drawing" in tags) or any(k in filename for k in ("图", "图纸", "施工图", "平面", "剖面", "大样", "节点"))
        is_excluded = any(k in filename for k in ("招标", "招標", "清单", "工程量清单")) or any(k in name for k in ("tender", "boq"))
        if not is_drawing or is_excluded:
            continue
        saved_as = rec.get("saved_as")
        if not saved_as:
            continue
        sp = Path(saved_as)
        if not sp.exists():
            continue
        picks.append(rec)

    out_paths: List[str] = []
    for rec in picks:
        if len(out_paths) >= max(0, int(limit or 0)):
            break
        p = rec.get("preview_saved_as")
        if isinstance(p, str) and p.strip() and Path(p).exists():
            out_paths.append(p)
            continue
        # On-the-fly preview (best-effort)
        saved_as = Path(rec.get("saved_as") or "")
        if not saved_as.exists():
            continue
        suffix = saved_as.suffix.lower()
        safe_name = re.sub(r"[^A-Za-z0-9_\\-\\.]+", "_", (rec.get("filename") or "doc"))[:80]
        out = MEDIA_DIR / f"ingest_{rec.get('sha256','')[:8]}_{safe_name}.png"
        try:
            if suffix in {".png", ".jpg", ".jpeg"}:
                from PIL import Image

                with Image.open(saved_as) as im:
                    im = im.convert("RGB")
                    if im.width > 1400:
                        h = int(im.height * (1400 / max(1, im.width)))
                        im = im.resize((1400, max(1, h)))
                    im.save(out, format="PNG")
                out_paths.append(str(out))
            elif suffix == ".pdf":
                import pypdfium2 as pdfium

                pdf = pdfium.PdfDocument(str(saved_as))
                if len(pdf) <= 0:
                    continue
                page = pdf[0]
                bitmap = page.render(scale=2.0)
                im = bitmap.to_pil()
                try:
                    pdf.close()
                except Exception:
                    pass
                if im.width > 1600:
                    from PIL import Image

                    h = int(im.height * (1600 / max(1, im.width)))
                    im = im.resize((1600, max(1, h)), resample=Image.BICUBIC)
                im.save(out, format="PNG")
                out_paths.append(str(out))
        except Exception:
            continue
    return out_paths[: max(0, int(limit or 0))]


def generate_outline_mindmap(
    topic: str,
    outline: List[str],
    *,
    api_key: str | None = None,
    model: str | None = None,
    aspect_ratio: str = "16:9",
    logo_path: str | None = None,
    bidder_company: str | None = None,
    logo_url: str | None = None,
    bidder_domain: str | None = None,
) -> Dict[str, Any] | None:
    """
    Generate a mindmap image for the tender-derived outline.
    - Prefer Gemini native image generation when api_key is provided.
    - Fallback to deterministic matplotlib drawing if not.
    Returns a media dict: {"path": "...png", "caption": "..."}.
    """
    topic = str(topic or "施组方案").strip()
    outline = [str(x).strip() for x in (outline or []) if str(x).strip()][:18]
    if not outline:
        return None

    # Resolve logo (optional)
    if logo_path:
        try:
            from pathlib import Path as _P

            if not _P(str(logo_path)).exists():
                logo_path = None
        except Exception:
            logo_path = None
    if not logo_path and (bidder_company or logo_url or bidder_domain):
        try:
            from backend.zhifei_autoplan.logo_runtime import resolve_logo

            logo_path = resolve_logo(bidder_company=bidder_company, logo_url=logo_url, bidder_domain=bidder_domain)
        except Exception:
            logo_path = None

    # Try Gemini image model (Nano Banana) first
    if api_key:
        try:
            from backend.zhifei_autoplan.image_runtime import generate_image_gemini
            from backend.zhifei_autoplan.ocr_runtime import is_tesseract_available, guess_ocr_lang

            banned = "加强、确保、严格、压实责任、形成合力、高质量推进、提高政治站位、全力以赴"
            outline_text = "；".join(outline)
            prompt = (
                "生成一张中文信息图：标题为“施工组织设计思维导图”。"
                "画面风格：白底、蓝灰线条、工程图纸风格；结构清晰。"
                f"根节点：{topic}。"
                f"一级节点（必须全部出现）：{outline_text}。"
                "每个一级节点下给出3个二级节点：量化指标、风险闭环、证据台账（用短句）。"
                f"文字要求：不得出现官话/套话，禁用词：{banned}。"
                "如果提供了公司LOGO图片，请把该LOGO放在右上角，不改变LOGO形状。"
            )
            resp = generate_image_gemini(
                prompt=prompt,
                api_key=str(api_key),
                model=model,
                aspect_ratio=aspect_ratio,
                input_image_paths=[logo_path] if logo_path else None,
                out_dir=str(MEDIA_DIR),
            )
            if isinstance(resp, dict) and resp.get("ok") and resp.get("paths"):
                # Optional OCR gate: if the generated image contains banned phrases, fallback to deterministic drawing.
                try:
                    if is_tesseract_available():
                        import pytesseract
                        from PIL import Image
                        from backend.zhifei_autoplan.quality_check import OFFICIALESE_PHRASES, HARD_BANNED_WORDS

                        img_path = resp["paths"][0]
                        with Image.open(img_path) as im:
                            txt = pytesseract.image_to_string(im, lang=guess_ocr_lang(prefer_chinese=True))
                        if any(p in (txt or "") for p in (OFFICIALESE_PHRASES + HARD_BANNED_WORDS)):
                            raise ValueError("banned_phrase_in_image")
                except Exception:
                    resp = None
                if resp and resp.get("paths"):
                    return {"path": resp["paths"][0], "caption": "施工组织设计思维导图（Gemini）"}
        except Exception:
            pass

    # Fallback: deterministic diagram (no external API)
    try:
        import math
        from PIL import Image, ImageDraw, ImageFont

        w, h = 1600, 900
        im = Image.new("RGB", (w, h), color=(255, 255, 255))
        draw = ImageDraw.Draw(im)

        # Fonts: best-effort; do not hard-fail on missing fonts.
        def _load_font(size: int):
            for name in ("PingFang SC", "Hiragino Sans GB", "STHeiti", "SimHei", "Arial Unicode MS"):
                try:
                    return ImageFont.truetype(name, size=size)
                except Exception:
                    continue
            return ImageFont.load_default()

        f_title = _load_font(44)
        f_node = _load_font(28)
        f_sub = _load_font(22)

        # Title
        draw.text((60, 40), "施工组织设计思维导图", fill=(20, 40, 70), font=f_title)
        draw.text((60, 96), topic, fill=(40, 60, 90), font=f_node)

        # Simple radial layout for chapter nodes
        cx, cy = w // 2, h // 2 + 60
        r = 260
        n = max(1, len(outline))
        for i, title in enumerate(outline):
            ang = (2 * math.pi) * (i / n) - math.pi / 2
            x = int(cx + r * math.cos(ang))
            y = int(cy + r * math.sin(ang))

            # connector
            draw.line((cx, cy, x, y), fill=(160, 190, 220), width=4)

            # node box
            box_w, box_h = 360, 120
            bx0 = x - box_w // 2
            by0 = y - box_h // 2
            bx1 = bx0 + box_w
            by1 = by0 + box_h
            draw.rounded_rectangle((bx0, by0, bx1, by1), radius=18, outline=(60, 110, 170), width=4, fill=(245, 250, 255))
            draw.text((bx0 + 16, by0 + 12), title[:14], fill=(20, 40, 70), font=f_node)
            draw.text((bx0 + 16, by0 + 56), "量化指标 | 风险闭环 | 证据台账", fill=(60, 80, 110), font=f_sub)

        # center node
        draw.ellipse((cx - 120, cy - 70, cx + 120, cy + 70), outline=(20, 80, 140), width=6, fill=(230, 245, 255))
        draw.text((cx - 92, cy - 18), "总体", fill=(20, 40, 70), font=f_node)

        # Paste logo (optional) at top-right
        if logo_path:
            try:
                from PIL import Image as PILImage

                lp = Path(logo_path)
                if lp.exists():
                    with PILImage.open(lp) as logo:
                        logo = logo.convert("RGBA")
                        # scale to fit
                        max_w = 220
                        if logo.width > max_w:
                            hh = int(logo.height * (max_w / max(1, logo.width)))
                            logo = logo.resize((max_w, max(1, hh)))
                        x0 = w - logo.width - 60
                        y0 = 40
                        im.paste(logo, (x0, y0), mask=logo)
            except Exception:
                pass

        fname = f"mindmap_{int(time.time())}.png"
        out = MEDIA_DIR / fname
        im.save(out, format="PNG")
        return {"path": str(out), "caption": "施工组织设计思维导图（自动绘制）"}
    except Exception:
        return None
